const {test,expect}=require('@playwright/test');
test('intro persists; tap and long-press explain skills without selecting commands',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('/');await page.locator('#bootStart').tap();
 await expect(page.locator('#journeyResultTitle')).toContainText('森の奥');
 await page.locator('#journeyResultPrimary').tap();
 await expect(page.locator('#story')).toHaveClass(/show/);
 await page.reload();await page.locator('#bootStart').tap();
 await expect(page.locator('#journeyResult')).not.toHaveClass(/show/);
 await page.evaluate(()=>ML.go('boss'));
 const gouraCard=page.locator('#bossParty .formalUnit').filter({hasText:'ゴウラ'});
 await expect(gouraCard.locator('.skillInfo')).toHaveCount(0);
 await gouraCard.locator('.unitInspect').tap();
 await expect(page.locator('#sheetBody')).toContainText('STANCE');
 await expect(page.locator('#sheetBody')).toContainText('45%');
 await expect(page.locator('#bossQueue .ql')).toHaveCount(0);
 await page.locator('#sheetBody .btn').tap();
 const skill=page.locator('#bossParty .commandTile[data-help-unit="fire"][data-help-kind="CORE"]');
 await skill.scrollIntoViewIfNeeded();
 await skill.dispatchEvent('pointerdown',{button:0,pointerType:'mouse',clientX:1,clientY:1});
 await page.waitForTimeout(550);
 await skill.dispatchEvent('pointerup',{button:0,pointerType:'mouse',clientX:1,clientY:1});
 await expect(page.locator('#sheetBody')).toContainText('火牙');
 await expect(page.locator('#bossQueue .ql')).toHaveCount(0);
 await page.locator('#sheetBody .btn').tap();
 await skill.tap();await expect(page.locator('#bossQueue .ql')).toHaveCount(1);
 expect(errors).toEqual([]);
});