const { test, expect } = require('@playwright/test');
test('START → HOME → HUNT: two actual touch commands and a resolved turn', async ({ page }) => {
  const errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto('/');
  await page.locator('#bootStart').tap();
  await expect(page.locator('#journeyResult')).toHaveClass(/show/);
  await page.locator('#journeyResultPrimary').tap();
  await expect(page.locator('#story')).toHaveClass(/show/);
  // STORY intentionally hides global navigation: complete the actual tutorial route.
  await page.locator('[onclick="ML.storyNext()"]').tap();
  await page.locator('[onclick="ML.storyCmd(this)"][data-unit="goura"]').tap();
  await page.locator('[onclick="ML.storyCmd(this)"][data-unit="fire"]').tap();
  await page.locator('[onclick="ML.storyStance(\'goura\')"]').tap();
  await page.locator('[onclick="ML.storyVol(\'calm\')"]').tap();
  await page.locator('[onclick="ML.storyEquip(\'bell\')"]').tap();
  await page.locator('[onclick="ML.storyBoss()"]').tap();
  await expect(page.locator('#journeyResultTitle')).toContainText('分からなかった');
  await page.locator('#journeyResultPrimary').tap();
  await expect(page.locator('#home')).toHaveClass(/show/);
  await page.locator('.nav [data-go="hunt"]').tap();
  await expect(page.locator('#journeyResultTitle')).toContainText('開口を探す');
  await page.locator('#journeyResultPrimary').tap();
  await expect(page.locator('#hunt')).toHaveClass(/show/);
  await expect(page.locator('#huntStickyHpText')).toBeVisible();
  await expect(page.locator('#huntStickyVolText')).toBeVisible();
  const hp=await page.locator('#huntHpText').textContent();
  await page.locator('#huntParty [onclick="ML.openHunt(\'fire\')"]').tap();
  await page.locator('#sheetBody [data-uid="fire"][data-kind="CORE"]').tap();
  await expect(page.locator('#huntQueue .ql')).toHaveCount(1);
  await page.locator('#huntParty [onclick="ML.openHunt(\'goura\')"]').tap();
  await page.locator('#sheetBody [data-uid="goura"][data-kind="CORE"]').tap();
  await expect(page.locator('#huntQueue .ql')).toHaveCount(2);
  await expect(page.locator('#huntFieldParty .stance')).toHaveCount(1);
  await page.locator('#huntExec').tap();
  await expect(page.locator('#huntQueue .ql')).toHaveCount(0);
  await expect(page.locator('#huntHpText')).not.toHaveText(hp);
  expect(errors).toEqual([]);
});
